#!/bin/bash

# This script is used to switch between different alsa configuration files
#
# autor: Florin Hillebrand

VERSION="0.5"
THIS=$(dirname $0)
PRESETSFOLDER="$HOME/.alsapresets"

printUsage () {
	echo "Usage: aconfswitch -p PRESETNAME [OPTIONS]"
	echo "		OPTIONS		Can be a set of this options:"
	echo "			-p PRESETNAME		Name of the preset stored in audioPresets folder."
	echo "			-k			Keep line after the first match "
	echo "						with 'Master Playback Volume'"
	echo "						from the old preset."
	echo "			-i			Print informations about this script."
	echo "			-v			Print version number."
	echo -e "\nExample: aconfswitch desktop	For the configuration file"
	echo "						~/.alsapresets/desktop.conf"
}

printInfo () {
	echo "This program is used to switch between different alsa configuration files."
	echo "It searchs for configuration files with the specified PRESETNAME appended"
	echo "by a '.conf' in the directory .alsapresets located in your home directory."
	echo "alsactl is used to switch between presets."
	echo "Create a configuration file by calling alsactl -f FILENAME.conf store."
	echo "Autor: Florin Hillebrand"
}

if [ $# -lt "1" ]; then
	echo -e "Wrong usage.\n" >&2
	printUsage
	exit 1
fi

while getopts ":hivkp:" opt; do
	case $opt in
		h)
			printInfo
			echo -ne "\n"
			printUsage
			exit 0
		;;
		i)
			printInfo
			exit 0
		;;
		v)
			echo $VERSION
			exit 0
		;;
		p)
			if [ -n "$preset_name" ]; then	
				echo "Preset name already specified" >&2
				exit 1
			fi
			preset_name=$OPTARG
			preset_file="$PRESETSFOLDER/$preset_name.conf"

			if [ ! -f "$preset_file" ]; then
				echo "Could not find audio preset configuration file in $preset_file." >&2
				exit 1
			fi

		;;
		k)
			keep_volume=1
		;;
		\?)
			echo "Invalid option -$opt." >&2
			exit 1
		;;
	esac
done

if [ -z $preset_name ]; then
	echo -e "Preset name not specified.\n" >&2
	printUsage
	exit 1
fi

# keep volume NOT set
if [ -z $keep_volume ]; then
	# apply new preset
	alsactl -f $preset_file restore

# keep volume set
else
	# get current master volume level
	current_volume_value=`amixer sget Master | grep "Mono:" | cut -d' ' -f5`

	# apply new preset
        alsactl -f $preset_file restore

	# set old volume level
	amixer sset Master $current_volume_value
fi
exit 0
